const vehicleData = {
    'Total Kendaraan': {
      data: {
        Andir: 332,
        Antapani: 353,
        Arcamanik: 346,
        AstanaAnyar: 396,
        BabakanCiparay: 403,
        BandungKidul: 582,
        BandungWetan: 421,
        Batununggal: 220,
        Ujungberung: 281,
        SumurBandung: 230,
        BojongloaKaler: 438,
        BojongloaKidul: 516,
        Buahbatu: 263,
        CibeunyingKaler: 311,
        CibeunyingKidul: 174,
        Cibiru: 329,
        Cicendo: 169,
        Cidadap: 186,
        Cinambo: 363,
        Coblong: 206,
        Gedebage: 255,
        Kiaracondong: 884,
        Lengkong: 163,
        Mandalajati: 260,
        Panyileukan: 342,
        Rancasari: 392,
        Regol: 351,
        Sukajadi: 443,
        Sukasari: 580,
      },
      rataRata: 346.80,
      standarDeviasi: 152.58,
      batasAtas: 423.09,
      batasBawah: 270.51,
    },
    'Agya': {
      data: {
        Andir: 3,
        Antapani: 10,
        Arcamanik: 7,
        AstanaAnyar: 4,
        BabakanCiparay: 7,
        BandungKidul: 14,
        BandungKulon: 12,
        BandungWetan: 3,
        Batununggal: 6,
        BojongloaKaler: 7,
        BojongloaKidul: 14,
        Buahbatu: 10,
        CibeunyingKaler: 5,
        CibeunyingKidul: 8,
        Cibiru: 8,
        Cicendo: 9,
        Cidadap: 6,
        Cinambo: 3,
        Coblong: 9,
        Gedebage: 5,
        Kiaracondong: 2,
        Lengkong: 11,
        Mandalajati: 5,
        Panyileukan: 4,
        Rancasari: 10,
        Regol: 19,
        Sukajadi: 5,
        Sukasari: 11,
        SumurBandung: 5,
        Ujungberung: 8,
      },
      rataRata: 7.67,
      standarDeviasi: 3.88,
      batasAtas: 9.61,
      batasBawah: 5.73,
    },
  };
  
  export default vehicleData;
  